### ISSUE TITLE
Clarify what permissions are needed

### ISSUE THREAD

**Issue by sirnacnud** [GrantBirki/pr-status#23]
I was having trouble getting the action working. The GraphQL query in `status.js` was failing with `Resource not accessible by integration`.

I have these permissions on the workflow and it is working now.
```
permissions:
  contents: read
  checks: read
  statuses: read
  pull-requests: read
```

Are you able to clarify which permissions are actually needed by the action?
